language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

deploy:
  provider: pages
  skip_cleanup: true
  github_token: IvwD44qu8J5C-TUsnv5TiA
  keep_history: true
  edge: true
  token: IvwD44qu8J5C-TUsnv5TiA
  local_dir: src/main/webapp/
  on:
    branch: master
