language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  edge: true
  on:
    branch: master
